### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode - Can't intergrate with my Express app "use strict"; error

### ISSUE THREAD

**Issue by alexrmacleod** [vankasteelj/opensubtitles-api#25]
I get this when trying to run my Express app `OpenSubtitles.api.LogIn(` without `"use strict";`

```
/Users/alex/Dropbox/Linkcast/subtitle/node_modules/opensubtitles-api/lib/opensubtitles.js:10
module.exports = class OS {
                 ^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/alex/Dropbox/Linkcast/subtitle/node_modules/opensubtitles-api/index.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

Then I try to run it with `"use strict";` or `node --use_strict app.js` I get the below error. 

```
/Users/alex/Dropbox/Linkcast/subtitle/node_modules/opensubtitles-api/lib/opensubtitles.js:36
            this.client.methodCall(method, [...args], (err, data) => {
                                            ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/alex/Dropbox/Linkcast/subtitle/node_modules/opensubtitles-api/index.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

Does this npm module work with express? can someone explain how to integrate this? spending way too long trying to run `OpenSubtitles.api.LogIn(`

**Comment by alexrmacleod** [comment]
Oh I needed to update node to 6.10.3

**Comment by vankasteelj** [comment]
Yes, I made an update to es6/7 instead of es5
